// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gamingplatform/api/chat/v1/messaging.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateChat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Authors        []string               `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateChat) Reset() {
	*x = InitiateChat{}
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateChat) ProtoMessage() {}

func (x *InitiateChat) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateChat.ProtoReflect.Descriptor instead.
func (*InitiateChat) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_chat_v1_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateChat) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InitiateChat) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InitiateChat) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

type InitiateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateChatResponse) Reset() {
	*x = InitiateChatResponse{}
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateChatResponse) ProtoMessage() {}

func (x *InitiateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateChatResponse.ProtoReflect.Descriptor instead.
func (*InitiateChatResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_chat_v1_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *InitiateChatResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type WriteMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This applies per author within a chat.
	// Don't set if no idempotency is needed.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ChatId         string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AuthorId       string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Message        string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteMessage) Reset() {
	*x = WriteMessage{}
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMessage) ProtoMessage() {}

func (x *WriteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMessage.ProtoReflect.Descriptor instead.
func (*WriteMessage) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_chat_v1_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *WriteMessage) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WriteMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *WriteMessage) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *WriteMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WriteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMessageResponse) Reset() {
	*x = WriteMessageResponse{}
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMessageResponse) ProtoMessage() {}

func (x *WriteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMessageResponse.ProtoReflect.Descriptor instead.
func (*WriteMessageResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_chat_v1_messaging_proto_rawDescGZIP(), []int{3}
}

type MessageWritten struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChatId    string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	AuthorId  string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Specifies the date and time the message was written in ISO 8601 format.
	WrittenAt     string `protobuf:"bytes,4,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWritten) Reset() {
	*x = MessageWritten{}
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWritten) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWritten) ProtoMessage() {}

func (x *MessageWritten) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_chat_v1_messaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWritten.ProtoReflect.Descriptor instead.
func (*MessageWritten) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_chat_v1_messaging_proto_rawDescGZIP(), []int{4}
}

func (x *MessageWritten) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MessageWritten) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageWritten) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *MessageWritten) GetWrittenAt() string {
	if x != nil {
		return x.WrittenAt
	}
	return ""
}

func (x *MessageWritten) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gamingplatform_api_chat_v1_messaging_proto protoreflect.FileDescriptor

const file_gamingplatform_api_chat_v1_messaging_proto_rawDesc = "" +
	"\n" +
	"*gamingplatform/api/chat/v1/messaging.proto\x12\x1agamingplatform.api.chat.v1\"x\n" +
	"\fInitiateChat\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\aauthors\x18\x03 \x03(\tR\aauthors\"V\n" +
	"\x14InitiateChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"\x87\x01\n" +
	"\fWriteMessage\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x16\n" +
	"\x14WriteMessageResponse\"\x9e\x01\n" +
	"\x0eMessageWritten\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x1d\n" +
	"\n" +
	"written_at\x18\x04 \x01(\tR\twrittenAt\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessageBxZ0github.com/gaming-platform/api/go/chat/v1;chatv1\xca\x02\x1aGamingPlatform\\Api\\Chat\\V1\xe2\x02&GamingPlatform\\Api\\GPBMetadata\\Chat\\V1b\x06proto3"

var (
	file_gamingplatform_api_chat_v1_messaging_proto_rawDescOnce sync.Once
	file_gamingplatform_api_chat_v1_messaging_proto_rawDescData []byte
)

func file_gamingplatform_api_chat_v1_messaging_proto_rawDescGZIP() []byte {
	file_gamingplatform_api_chat_v1_messaging_proto_rawDescOnce.Do(func() {
		file_gamingplatform_api_chat_v1_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamingplatform_api_chat_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_chat_v1_messaging_proto_rawDesc)))
	})
	return file_gamingplatform_api_chat_v1_messaging_proto_rawDescData
}

var file_gamingplatform_api_chat_v1_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gamingplatform_api_chat_v1_messaging_proto_goTypes = []any{
	(*InitiateChat)(nil),         // 0: gamingplatform.api.chat.v1.InitiateChat
	(*InitiateChatResponse)(nil), // 1: gamingplatform.api.chat.v1.InitiateChatResponse
	(*WriteMessage)(nil),         // 2: gamingplatform.api.chat.v1.WriteMessage
	(*WriteMessageResponse)(nil), // 3: gamingplatform.api.chat.v1.WriteMessageResponse
	(*MessageWritten)(nil),       // 4: gamingplatform.api.chat.v1.MessageWritten
}
var file_gamingplatform_api_chat_v1_messaging_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gamingplatform_api_chat_v1_messaging_proto_init() }
func file_gamingplatform_api_chat_v1_messaging_proto_init() {
	if File_gamingplatform_api_chat_v1_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamingplatform_api_chat_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_chat_v1_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamingplatform_api_chat_v1_messaging_proto_goTypes,
		DependencyIndexes: file_gamingplatform_api_chat_v1_messaging_proto_depIdxs,
		MessageInfos:      file_gamingplatform_api_chat_v1_messaging_proto_msgTypes,
	}.Build()
	File_gamingplatform_api_chat_v1_messaging_proto = out.File
	file_gamingplatform_api_chat_v1_messaging_proto_goTypes = nil
	file_gamingplatform_api_chat_v1_messaging_proto_depIdxs = nil
}
