<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/identity/v1/messaging.proto

namespace GamingPlatform\Api\GPBMetadata\Identity\V1;

class Messaging
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¢
.gamingplatform/api/identity/v1/messaging.protogamingplatform.api.identity.v1"
UserArrived
user_id (	"@
UserSignedUp
user_id (	
username (	
email (	BfZidentity/v1;identityv1ÊGamingPlatform\\Api\\Identity\\V1â*GamingPlatform\\Api\\GPBMetadata\\Identity\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

