#!/usr/bin/env bash

set -e

help() {
    echo
    echo ------------------
    echo Available commands
    echo ------------------
    echo protoc
    echo Generate language files with protoc.
    echo
}

protoc() {
    docker compose run --rm protoc
    docker run \
        --rm \
        -v $(pwd):/project \
        ghcr.io/gaming-platform/docker-php-fpm:8.3-development \
        /project/bin/generatePhpFactories
    docker compose run --rm protoc /project/bin/fixGoPaths
}

if [ "$*" = "" ]
then
    help
else
    $1 "${@:2}"
fi
