<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1\Game\Move;

use UnexpectedValueException;

/**
 * Protobuf type <code>gamingplatform.api.connectfour.v1.Game.Move.Color</code>
 */
class Color
{
    /**
     * Generated from protobuf enum <code>COLOR_UNSPECIFIED = 0;</code>
     */
    const COLOR_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>COLOR_RED = 1;</code>
     */
    const COLOR_RED = 1;
    /**
     * Generated from protobuf enum <code>COLOR_YELLOW = 2;</code>
     */
    const COLOR_YELLOW = 2;

    private static $valueToName = [
        self::COLOR_UNSPECIFIED => 'COLOR_UNSPECIFIED',
        self::COLOR_RED => 'COLOR_RED',
        self::COLOR_YELLOW => 'COLOR_YELLOW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Color::class, \GamingPlatform\Api\ConnectFour\V1\Game_Move_Color::class);

