<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1\OpenGame;

use UnexpectedValueException;

/**
 * Protobuf type <code>gamingplatform.api.connectfour.v1.OpenGame.Stone</code>
 */
class Stone
{
    /**
     * Generated from protobuf enum <code>STONE_UNSPECIFIED = 0;</code>
     */
    const STONE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>STONE_RED = 1;</code>
     */
    const STONE_RED = 1;
    /**
     * Generated from protobuf enum <code>STONE_YELLOW = 2;</code>
     */
    const STONE_YELLOW = 2;
    /**
     * Generated from protobuf enum <code>STONE_RANDOM = -1;</code>
     */
    const STONE_RANDOM = -1;

    private static $valueToName = [
        self::STONE_UNSPECIFIED => 'STONE_UNSPECIFIED',
        self::STONE_RED => 'STONE_RED',
        self::STONE_YELLOW => 'STONE_YELLOW',
        self::STONE_RANDOM => 'STONE_RANDOM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stone::class, \GamingPlatform\Api\ConnectFour\V1\OpenGame_Stone::class);

