<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1\GetOpenGamesResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.connectfour.v1.GetOpenGamesResponse.Game</code>
 */
class Game extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     */
    protected $game_id = '';
    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     */
    protected $width = 0;
    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>string player_id = 4;</code>
     */
    protected $player_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $game_id
     *     @type int $width
     *     @type int $height
     *     @type string $player_id
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\ConnectFour\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->game_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string player_id = 4;</code>
     * @return string
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * Generated from protobuf field <code>string player_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Game::class, \GamingPlatform\Api\ConnectFour\V1\GetOpenGamesResponse_Game::class);

