<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1\GetGamesByPlayer;

use UnexpectedValueException;

/**
 * Protobuf type <code>gamingplatform.api.connectfour.v1.GetGamesByPlayer.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>STATE_UNSPECIFIED = 0;</code>
     */
    const STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>STATE_ALL = 1;</code>
     */
    const STATE_ALL = 1;
    /**
     * Generated from protobuf enum <code>STATE_OPEN = 2;</code>
     */
    const STATE_OPEN = 2;
    /**
     * Generated from protobuf enum <code>STATE_RUNNING = 3;</code>
     */
    const STATE_RUNNING = 3;
    /**
     * Generated from protobuf enum <code>STATE_WON = 4;</code>
     */
    const STATE_WON = 4;
    /**
     * Generated from protobuf enum <code>STATE_LOST = 5;</code>
     */
    const STATE_LOST = 5;
    /**
     * Generated from protobuf enum <code>STATE_DRAWN = 6;</code>
     */
    const STATE_DRAWN = 6;

    private static $valueToName = [
        self::STATE_UNSPECIFIED => 'STATE_UNSPECIFIED',
        self::STATE_ALL => 'STATE_ALL',
        self::STATE_OPEN => 'STATE_OPEN',
        self::STATE_RUNNING => 'STATE_RUNNING',
        self::STATE_WON => 'STATE_WON',
        self::STATE_LOST => 'STATE_LOST',
        self::STATE_DRAWN => 'STATE_DRAWN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \GamingPlatform\Api\ConnectFour\V1\GetGamesByPlayer_State::class);

