// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gamingplatform/api/connectfour/v1/messaging.proto

package connectfourv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game_Move_Color int32

const (
	Game_Move_COLOR_UNSPECIFIED Game_Move_Color = 0
	Game_Move_RED               Game_Move_Color = 1
	Game_Move_YELLOW            Game_Move_Color = 2
)

// Enum value maps for Game_Move_Color.
var (
	Game_Move_Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "RED",
		2: "YELLOW",
	}
	Game_Move_Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"RED":               1,
		"YELLOW":            2,
	}
)

func (x Game_Move_Color) Enum() *Game_Move_Color {
	p := new(Game_Move_Color)
	*p = x
	return p
}

func (x Game_Move_Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_Move_Color) Descriptor() protoreflect.EnumDescriptor {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_enumTypes[0].Descriptor()
}

func (Game_Move_Color) Type() protoreflect.EnumType {
	return &file_gamingplatform_api_connectfour_v1_messaging_proto_enumTypes[0]
}

func (x Game_Move_Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_Move_Color.Descriptor instead.
func (Game_Move_Color) EnumDescriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{6, 0, 0}
}

type JoinGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGame) Reset() {
	*x = JoinGame{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame) ProtoMessage() {}

func (x *JoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame.ProtoReflect.Descriptor instead.
func (*JoinGame) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *JoinGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *JoinGame) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{1}
}

type MakeMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMove) Reset() {
	*x = MakeMove{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMove) ProtoMessage() {}

func (x *MakeMove) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMove.ProtoReflect.Descriptor instead.
func (*MakeMove) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *MakeMove) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeMove) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MakeMove) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{3}
}

type GetGamesByPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameState     string                 `protobuf:"bytes,2,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"` // "all", "running", "won, "lost", "drawn"
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByPlayer) Reset() {
	*x = GetGamesByPlayer{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByPlayer) ProtoMessage() {}

func (x *GetGamesByPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByPlayer.ProtoReflect.Descriptor instead.
func (*GetGamesByPlayer) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{4}
}

func (x *GetGamesByPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetGamesByPlayer) GetGameState() string {
	if x != nil {
		return x.GameState
	}
	return ""
}

func (x *GetGamesByPlayer) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGamesByPlayer) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGamesByPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByPlayerResponse) Reset() {
	*x = GetGamesByPlayerResponse{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByPlayerResponse) ProtoMessage() {}

func (x *GetGamesByPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetGamesByPlayerResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{5}
}

func (x *GetGamesByPlayerResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GetGamesByPlayerResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Game struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameId          string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RedPlayerId     string                 `protobuf:"bytes,2,opt,name=red_player_id,json=redPlayerId,proto3" json:"red_player_id,omitempty"`
	YellowPlayerId  string                 `protobuf:"bytes,3,opt,name=yellow_player_id,json=yellowPlayerId,proto3" json:"yellow_player_id,omitempty"`
	CurrentPlayerId string                 `protobuf:"bytes,4,opt,name=current_player_id,json=currentPlayerId,proto3" json:"current_player_id,omitempty"`
	Moves           []*Game_Move           `protobuf:"bytes,5,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{6}
}

func (x *Game) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Game) GetRedPlayerId() string {
	if x != nil {
		return x.RedPlayerId
	}
	return ""
}

func (x *Game) GetYellowPlayerId() string {
	if x != nil {
		return x.YellowPlayerId
	}
	return ""
}

func (x *Game) GetCurrentPlayerId() string {
	if x != nil {
		return x.CurrentPlayerId
	}
	return ""
}

func (x *Game) GetMoves() []*Game_Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type Game_Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Color         Game_Move_Color        `protobuf:"varint,3,opt,name=color,proto3,enum=gamingplatform.api.connectfour.v1.Game_Move_Color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game_Move) Reset() {
	*x = Game_Move{}
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_Move) ProtoMessage() {}

func (x *Game_Move) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_Move.ProtoReflect.Descriptor instead.
func (*Game_Move) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Game_Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Game_Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Game_Move) GetColor() Game_Move_Color {
	if x != nil {
		return x.Color
	}
	return Game_Move_COLOR_UNSPECIFIED
}

var File_gamingplatform_api_connectfour_v1_messaging_proto protoreflect.FileDescriptor

const file_gamingplatform_api_connectfour_v1_messaging_proto_rawDesc = "" +
	"\n" +
	"1gamingplatform/api/connectfour/v1/messaging.proto\x12!gamingplatform.api.connectfour.v1\"@\n" +
	"\bJoinGame\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x12\n" +
	"\x10JoinGameResponse\"X\n" +
	"\bMakeMove\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"\x12\n" +
	"\x10MakeMoveResponse\"x\n" +
	"\x10GetGamesByPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"game_state\x18\x02 \x01(\tR\tgameState\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"o\n" +
	"\x18GetGamesByPlayerResponse\x12=\n" +
	"\x05games\x18\x01 \x03(\v2'.gamingplatform.api.connectfour.v1.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x81\x03\n" +
	"\x04Game\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\"\n" +
	"\rred_player_id\x18\x02 \x01(\tR\vredPlayerId\x12(\n" +
	"\x10yellow_player_id\x18\x03 \x01(\tR\x0eyellowPlayerId\x12*\n" +
	"\x11current_player_id\x18\x04 \x01(\tR\x0fcurrentPlayerId\x12B\n" +
	"\x05moves\x18\x05 \x03(\v2,.gamingplatform.api.connectfour.v1.Game.MoveR\x05moves\x1a\xa1\x01\n" +
	"\x04Move\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12H\n" +
	"\x05color\x18\x03 \x01(\x0e22.gamingplatform.api.connectfour.v1.Game.Move.ColorR\x05color\"3\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RED\x10\x01\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x02B\x94\x01Z>github.com/gaming-platform/api/go/connectfour/v1;connectfourv1\xca\x02!GamingPlatform\\Api\\ConnectFour\\V1\xe2\x02-GamingPlatform\\Api\\GPBMetadata\\ConnectFour\\V1b\x06proto3"

var (
	file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescOnce sync.Once
	file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescData []byte
)

func file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescGZIP() []byte {
	file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescOnce.Do(func() {
		file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamingplatform_api_connectfour_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_connectfour_v1_messaging_proto_rawDesc)))
	})
	return file_gamingplatform_api_connectfour_v1_messaging_proto_rawDescData
}

var file_gamingplatform_api_connectfour_v1_messaging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gamingplatform_api_connectfour_v1_messaging_proto_goTypes = []any{
	(Game_Move_Color)(0),             // 0: gamingplatform.api.connectfour.v1.Game.Move.Color
	(*JoinGame)(nil),                 // 1: gamingplatform.api.connectfour.v1.JoinGame
	(*JoinGameResponse)(nil),         // 2: gamingplatform.api.connectfour.v1.JoinGameResponse
	(*MakeMove)(nil),                 // 3: gamingplatform.api.connectfour.v1.MakeMove
	(*MakeMoveResponse)(nil),         // 4: gamingplatform.api.connectfour.v1.MakeMoveResponse
	(*GetGamesByPlayer)(nil),         // 5: gamingplatform.api.connectfour.v1.GetGamesByPlayer
	(*GetGamesByPlayerResponse)(nil), // 6: gamingplatform.api.connectfour.v1.GetGamesByPlayerResponse
	(*Game)(nil),                     // 7: gamingplatform.api.connectfour.v1.Game
	(*Game_Move)(nil),                // 8: gamingplatform.api.connectfour.v1.Game.Move
}
var file_gamingplatform_api_connectfour_v1_messaging_proto_depIdxs = []int32{
	7, // 0: gamingplatform.api.connectfour.v1.GetGamesByPlayerResponse.games:type_name -> gamingplatform.api.connectfour.v1.Game
	8, // 1: gamingplatform.api.connectfour.v1.Game.moves:type_name -> gamingplatform.api.connectfour.v1.Game.Move
	0, // 2: gamingplatform.api.connectfour.v1.Game.Move.color:type_name -> gamingplatform.api.connectfour.v1.Game.Move.Color
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gamingplatform_api_connectfour_v1_messaging_proto_init() }
func file_gamingplatform_api_connectfour_v1_messaging_proto_init() {
	if File_gamingplatform_api_connectfour_v1_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamingplatform_api_connectfour_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_connectfour_v1_messaging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamingplatform_api_connectfour_v1_messaging_proto_goTypes,
		DependencyIndexes: file_gamingplatform_api_connectfour_v1_messaging_proto_depIdxs,
		EnumInfos:         file_gamingplatform_api_connectfour_v1_messaging_proto_enumTypes,
		MessageInfos:      file_gamingplatform_api_connectfour_v1_messaging_proto_msgTypes,
	}.Build()
	File_gamingplatform_api_connectfour_v1_messaging_proto = out.File
	file_gamingplatform_api_connectfour_v1_messaging_proto_goTypes = nil
	file_gamingplatform_api_connectfour_v1_messaging_proto_depIdxs = nil
}
