<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/chat/v1/messaging.proto

namespace GamingPlatform\Api\GPBMetadata\Chat\V1;

class Messaging
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ì
*gamingplatform/api/chat/v1/messaging.protogamingplatform.api.chat.v1"P
InitiateChat
idempotency_key (	
correlation_id (	
authors (	"?
InitiateChatResponse
chat_id (	
correlation_id (	"m
MessageWritten
chat_id (	

message_id (	
	author_id (	

written_at (	
message (	BxZ0github.com/gaming-platform/api/go/chat/v1;chatv1ÊGamingPlatform\\Api\\Chat\\V1â&GamingPlatform\\Api\\GPBMetadata\\Chat\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

