<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/common/v1/messaging.proto

namespace GamingPlatform\Api\Common\V1\Error;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.common.v1.Error.Violation</code>
 */
class Violation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string property_path = 1;</code>
     */
    protected $property_path = '';
    /**
     * Generated from protobuf field <code>string identifier = 2;</code>
     */
    protected $identifier = '';
    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.common.v1.Error.Violation.Parameter parameters = 3;</code>
     */
    private $parameters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $property_path
     *     @type string $identifier
     *     @type array<\GamingPlatform\Api\Common\V1\Error\Violation\Parameter>|\Google\Protobuf\Internal\RepeatedField $parameters
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Common\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string property_path = 1;</code>
     * @return string
     */
    public function getPropertyPath()
    {
        return $this->property_path;
    }

    /**
     * Generated from protobuf field <code>string property_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPropertyPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->property_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identifier = 2;</code>
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Generated from protobuf field <code>string identifier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.common.v1.Error.Violation.Parameter parameters = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.common.v1.Error.Violation.Parameter parameters = 3;</code>
     * @param array<\GamingPlatform\Api\Common\V1\Error\Violation\Parameter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GamingPlatform\Api\Common\V1\Error\Violation\Parameter::class);
        $this->parameters = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Violation::class, \GamingPlatform\Api\Common\V1\Error_Violation::class);

