<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1\Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.connectfour.v1.Game.Move</code>
 */
class Move extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 x = 1;</code>
     */
    protected $x = 0;
    /**
     * Generated from protobuf field <code>int32 y = 2;</code>
     */
    protected $y = 0;
    /**
     * Generated from protobuf field <code>.gamingplatform.api.connectfour.v1.Game.Move.Color color = 3;</code>
     */
    protected $color = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $x
     *     @type int $y
     *     @type int $color
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\ConnectFour\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 x = 1;</code>
     * @return int
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Generated from protobuf field <code>int32 x = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setX($var)
    {
        GPBUtil::checkInt32($var);
        $this->x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 y = 2;</code>
     * @return int
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>int32 y = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setY($var)
    {
        GPBUtil::checkInt32($var);
        $this->y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.connectfour.v1.Game.Move.Color color = 3;</code>
     * @return int
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.connectfour.v1.Game.Move.Color color = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkEnum($var, \GamingPlatform\Api\ConnectFour\V1\Game\Move\Color::class);
        $this->color = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Move::class, \GamingPlatform\Api\ConnectFour\V1\Game_Move::class);

