<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/chat/v1/messaging.proto

namespace GamingPlatform\Api\Chat\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.chat.v1.InitiateChatResponse</code>
 */
class InitiateChatResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string chat_id = 1;</code>
     */
    protected $chat_id = '';
    /**
     * Generated from protobuf field <code>string correlation_id = 2;</code>
     */
    protected $correlation_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $chat_id
     *     @type string $correlation_id
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Chat\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string chat_id = 1;</code>
     * @return string
     */
    public function getChatId()
    {
        return $this->chat_id;
    }

    /**
     * Generated from protobuf field <code>string chat_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chat_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string correlation_id = 2;</code>
     * @return string
     */
    public function getCorrelationId()
    {
        return $this->correlation_id;
    }

    /**
     * Generated from protobuf field <code>string correlation_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCorrelationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->correlation_id = $var;

        return $this;
    }

}

