<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/chat/v1/messaging.proto

namespace GamingPlatform\Api\Chat\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.chat.v1.InitiateChat</code>
 */
class InitiateChat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string idempotency_key = 1;</code>
     */
    protected $idempotency_key = '';
    /**
     * Generated from protobuf field <code>string correlation_id = 2;</code>
     */
    protected $correlation_id = '';
    /**
     * Generated from protobuf field <code>repeated string authors = 3;</code>
     */
    private $authors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $idempotency_key
     *     @type string $correlation_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $authors
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Chat\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 1;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string correlation_id = 2;</code>
     * @return string
     */
    public function getCorrelationId()
    {
        return $this->correlation_id;
    }

    /**
     * Generated from protobuf field <code>string correlation_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCorrelationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->correlation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string authors = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuthors()
    {
        return $this->authors;
    }

    /**
     * Generated from protobuf field <code>repeated string authors = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuthors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->authors = $arr;

        return $this;
    }

}

