<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/chat/v1/messaging.proto

namespace GamingPlatform\Api\Chat\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.chat.v1.MessageWritten</code>
 */
class MessageWritten extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string chat_id = 1;</code>
     */
    protected $chat_id = '';
    /**
     * Generated from protobuf field <code>string message_id = 2;</code>
     */
    protected $message_id = '';
    /**
     * Generated from protobuf field <code>string author_id = 3;</code>
     */
    protected $author_id = '';
    /**
     * Specifies the date and time the message was written in ISO 8601 format.
     *
     * Generated from protobuf field <code>string written_at = 4;</code>
     */
    protected $written_at = '';
    /**
     * Generated from protobuf field <code>string message = 5;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $chat_id
     *     @type string $message_id
     *     @type string $author_id
     *     @type string $written_at
     *           Specifies the date and time the message was written in ISO 8601 format.
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Chat\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string chat_id = 1;</code>
     * @return string
     */
    public function getChatId()
    {
        return $this->chat_id;
    }

    /**
     * Generated from protobuf field <code>string chat_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chat_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_id = 2;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * Generated from protobuf field <code>string message_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string author_id = 3;</code>
     * @return string
     */
    public function getAuthorId()
    {
        return $this->author_id;
    }

    /**
     * Generated from protobuf field <code>string author_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->author_id = $var;

        return $this;
    }

    /**
     * Specifies the date and time the message was written in ISO 8601 format.
     *
     * Generated from protobuf field <code>string written_at = 4;</code>
     * @return string
     */
    public function getWrittenAt()
    {
        return $this->written_at;
    }

    /**
     * Specifies the date and time the message was written in ISO 8601 format.
     *
     * Generated from protobuf field <code>string written_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWrittenAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->written_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 5;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

