<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/chat/v1/messaging.proto

namespace GamingPlatform\Api\Chat\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.chat.v1.WriteMessage</code>
 */
class WriteMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * This applies per author within a chat.
     * Don't set if no idempotency is needed.
     *
     * Generated from protobuf field <code>string idempotency_key = 1;</code>
     */
    protected $idempotency_key = '';
    /**
     * Generated from protobuf field <code>string chat_id = 2;</code>
     */
    protected $chat_id = '';
    /**
     * Generated from protobuf field <code>string author_id = 3;</code>
     */
    protected $author_id = '';
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $idempotency_key
     *           This applies per author within a chat.
     *           Don't set if no idempotency is needed.
     *     @type string $chat_id
     *     @type string $author_id
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Chat\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * This applies per author within a chat.
     * Don't set if no idempotency is needed.
     *
     * Generated from protobuf field <code>string idempotency_key = 1;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * This applies per author within a chat.
     * Don't set if no idempotency is needed.
     *
     * Generated from protobuf field <code>string idempotency_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chat_id = 2;</code>
     * @return string
     */
    public function getChatId()
    {
        return $this->chat_id;
    }

    /**
     * Generated from protobuf field <code>string chat_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chat_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string author_id = 3;</code>
     * @return string
     */
    public function getAuthorId()
    {
        return $this->author_id;
    }

    /**
     * Generated from protobuf field <code>string author_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->author_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

