// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gamingplatform/api/common/v1/messaging.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Violations    []*ErrorResponse_Violation `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_gamingplatform_api_common_v1_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_common_v1_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_common_v1_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetViolations() []*ErrorResponse_Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type ErrorResponse_Violation struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	PropertyPath  string                               `protobuf:"bytes,1,opt,name=property_path,json=propertyPath,proto3" json:"property_path,omitempty"`
	Identifier    string                               `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Parameters    []*ErrorResponse_Violation_Parameter `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse_Violation) Reset() {
	*x = ErrorResponse_Violation{}
	mi := &file_gamingplatform_api_common_v1_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse_Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse_Violation) ProtoMessage() {}

func (x *ErrorResponse_Violation) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_common_v1_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse_Violation.ProtoReflect.Descriptor instead.
func (*ErrorResponse_Violation) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_common_v1_messaging_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ErrorResponse_Violation) GetPropertyPath() string {
	if x != nil {
		return x.PropertyPath
	}
	return ""
}

func (x *ErrorResponse_Violation) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ErrorResponse_Violation) GetParameters() []*ErrorResponse_Violation_Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ErrorResponse_Violation_Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ErrorResponse_Violation_Parameter_BoolValue
	//	*ErrorResponse_Violation_Parameter_IntValue
	//	*ErrorResponse_Violation_Parameter_FloatValue
	//	*ErrorResponse_Violation_Parameter_StringValue
	Value         isErrorResponse_Violation_Parameter_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse_Violation_Parameter) Reset() {
	*x = ErrorResponse_Violation_Parameter{}
	mi := &file_gamingplatform_api_common_v1_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse_Violation_Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse_Violation_Parameter) ProtoMessage() {}

func (x *ErrorResponse_Violation_Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_common_v1_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse_Violation_Parameter.ProtoReflect.Descriptor instead.
func (*ErrorResponse_Violation_Parameter) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_common_v1_messaging_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ErrorResponse_Violation_Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ErrorResponse_Violation_Parameter) GetValue() isErrorResponse_Violation_Parameter_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ErrorResponse_Violation_Parameter) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ErrorResponse_Violation_Parameter_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ErrorResponse_Violation_Parameter) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ErrorResponse_Violation_Parameter_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *ErrorResponse_Violation_Parameter) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*ErrorResponse_Violation_Parameter_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *ErrorResponse_Violation_Parameter) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ErrorResponse_Violation_Parameter_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isErrorResponse_Violation_Parameter_Value interface {
	isErrorResponse_Violation_Parameter_Value()
}

type ErrorResponse_Violation_Parameter_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ErrorResponse_Violation_Parameter_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ErrorResponse_Violation_Parameter_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ErrorResponse_Violation_Parameter_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*ErrorResponse_Violation_Parameter_BoolValue) isErrorResponse_Violation_Parameter_Value() {}

func (*ErrorResponse_Violation_Parameter_IntValue) isErrorResponse_Violation_Parameter_Value() {}

func (*ErrorResponse_Violation_Parameter_FloatValue) isErrorResponse_Violation_Parameter_Value() {}

func (*ErrorResponse_Violation_Parameter_StringValue) isErrorResponse_Violation_Parameter_Value() {}

var File_gamingplatform_api_common_v1_messaging_proto protoreflect.FileDescriptor

const file_gamingplatform_api_common_v1_messaging_proto_rawDesc = "" +
	"\n" +
	",gamingplatform/api/common/v1/messaging.proto\x12\x1cgamingplatform.api.common.v1\"\xcd\x03\n" +
	"\rErrorResponse\x12U\n" +
	"\n" +
	"violations\x18\x01 \x03(\v25.gamingplatform.api.common.v1.ErrorResponse.ViolationR\n" +
	"violations\x1a\xe4\x02\n" +
	"\tViolation\x12#\n" +
	"\rproperty_path\x18\x01 \x01(\tR\fpropertyPath\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12_\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2?.gamingplatform.api.common.v1.ErrorResponse.Violation.ParameterR\n" +
	"parameters\x1a\xb0\x01\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05valueB\x80\x01Z4github.com/gaming-platform/api/go/common/v1;commonv1\xca\x02\x1cGamingPlatform\\Api\\Common\\V1\xe2\x02(GamingPlatform\\Api\\GPBMetadata\\Common\\V1b\x06proto3"

var (
	file_gamingplatform_api_common_v1_messaging_proto_rawDescOnce sync.Once
	file_gamingplatform_api_common_v1_messaging_proto_rawDescData []byte
)

func file_gamingplatform_api_common_v1_messaging_proto_rawDescGZIP() []byte {
	file_gamingplatform_api_common_v1_messaging_proto_rawDescOnce.Do(func() {
		file_gamingplatform_api_common_v1_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamingplatform_api_common_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_common_v1_messaging_proto_rawDesc)))
	})
	return file_gamingplatform_api_common_v1_messaging_proto_rawDescData
}

var file_gamingplatform_api_common_v1_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gamingplatform_api_common_v1_messaging_proto_goTypes = []any{
	(*ErrorResponse)(nil),                     // 0: gamingplatform.api.common.v1.ErrorResponse
	(*ErrorResponse_Violation)(nil),           // 1: gamingplatform.api.common.v1.ErrorResponse.Violation
	(*ErrorResponse_Violation_Parameter)(nil), // 2: gamingplatform.api.common.v1.ErrorResponse.Violation.Parameter
}
var file_gamingplatform_api_common_v1_messaging_proto_depIdxs = []int32{
	1, // 0: gamingplatform.api.common.v1.ErrorResponse.violations:type_name -> gamingplatform.api.common.v1.ErrorResponse.Violation
	2, // 1: gamingplatform.api.common.v1.ErrorResponse.Violation.parameters:type_name -> gamingplatform.api.common.v1.ErrorResponse.Violation.Parameter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gamingplatform_api_common_v1_messaging_proto_init() }
func file_gamingplatform_api_common_v1_messaging_proto_init() {
	if File_gamingplatform_api_common_v1_messaging_proto != nil {
		return
	}
	file_gamingplatform_api_common_v1_messaging_proto_msgTypes[2].OneofWrappers = []any{
		(*ErrorResponse_Violation_Parameter_BoolValue)(nil),
		(*ErrorResponse_Violation_Parameter_IntValue)(nil),
		(*ErrorResponse_Violation_Parameter_FloatValue)(nil),
		(*ErrorResponse_Violation_Parameter_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamingplatform_api_common_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_common_v1_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamingplatform_api_common_v1_messaging_proto_goTypes,
		DependencyIndexes: file_gamingplatform_api_common_v1_messaging_proto_depIdxs,
		MessageInfos:      file_gamingplatform_api_common_v1_messaging_proto_msgTypes,
	}.Build()
	File_gamingplatform_api_common_v1_messaging_proto = out.File
	file_gamingplatform_api_common_v1_messaging_proto_goTypes = nil
	file_gamingplatform_api_common_v1_messaging_proto_depIdxs = nil
}
