// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gamingplatform/api/identity/v1/messaging.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserArrived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserArrived) Reset() {
	*x = UserArrived{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserArrived) ProtoMessage() {}

func (x *UserArrived) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserArrived.ProtoReflect.Descriptor instead.
func (*UserArrived) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *UserArrived) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserSignedUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignedUp) Reset() {
	*x = UserSignedUp{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignedUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignedUp) ProtoMessage() {}

func (x *UserSignedUp) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignedUp.ProtoReflect.Descriptor instead.
func (*UserSignedUp) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *UserSignedUp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSignedUp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSignedUp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterBot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBot) Reset() {
	*x = RegisterBot{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBot) ProtoMessage() {}

func (x *RegisterBot) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBot.ProtoReflect.Descriptor instead.
func (*RegisterBot) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBot) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RegisterBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBotResponse) Reset() {
	*x = RegisterBotResponse{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotResponse) ProtoMessage() {}

func (x *RegisterBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotResponse.ProtoReflect.Descriptor instead.
func (*RegisterBotResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterBotResponse) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type GetBotByUsername struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotByUsername) Reset() {
	*x = GetBotByUsername{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotByUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotByUsername) ProtoMessage() {}

func (x *GetBotByUsername) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotByUsername.ProtoReflect.Descriptor instead.
func (*GetBotByUsername) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{4}
}

func (x *GetBotByUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetBotByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *Bot                   `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotByUsernameResponse) Reset() {
	*x = GetBotByUsernameResponse{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotByUsernameResponse) ProtoMessage() {}

func (x *GetBotByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotByUsernameResponse.ProtoReflect.Descriptor instead.
func (*GetBotByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{5}
}

func (x *GetBotByUsernameResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{6}
}

func (x *Bot) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *Bot) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_gamingplatform_api_identity_v1_messaging_proto protoreflect.FileDescriptor

const file_gamingplatform_api_identity_v1_messaging_proto_rawDesc = "" +
	"\n" +
	".gamingplatform/api/identity/v1/messaging.proto\x12\x1egamingplatform.api.identity.v1\"&\n" +
	"\vUserArrived\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\fUserSignedUp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\")\n" +
	"\vRegisterBot\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\",\n" +
	"\x13RegisterBotResponse\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\".\n" +
	"\x10GetBotByUsername\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"Q\n" +
	"\x18GetBotByUsernameResponse\x125\n" +
	"\x03bot\x18\x01 \x01(\v2#.gamingplatform.api.identity.v1.BotR\x03bot\"8\n" +
	"\x03Bot\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busernameBfZ\x16identity/v1;identityv1\xca\x02\x1eGamingPlatform\\Api\\Identity\\V1\xe2\x02*GamingPlatform\\Api\\GPBMetadata\\Identity\\V1b\x06proto3"

var (
	file_gamingplatform_api_identity_v1_messaging_proto_rawDescOnce sync.Once
	file_gamingplatform_api_identity_v1_messaging_proto_rawDescData []byte
)

func file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP() []byte {
	file_gamingplatform_api_identity_v1_messaging_proto_rawDescOnce.Do(func() {
		file_gamingplatform_api_identity_v1_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc)))
	})
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescData
}

var file_gamingplatform_api_identity_v1_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gamingplatform_api_identity_v1_messaging_proto_goTypes = []any{
	(*UserArrived)(nil),              // 0: gamingplatform.api.identity.v1.UserArrived
	(*UserSignedUp)(nil),             // 1: gamingplatform.api.identity.v1.UserSignedUp
	(*RegisterBot)(nil),              // 2: gamingplatform.api.identity.v1.RegisterBot
	(*RegisterBotResponse)(nil),      // 3: gamingplatform.api.identity.v1.RegisterBotResponse
	(*GetBotByUsername)(nil),         // 4: gamingplatform.api.identity.v1.GetBotByUsername
	(*GetBotByUsernameResponse)(nil), // 5: gamingplatform.api.identity.v1.GetBotByUsernameResponse
	(*Bot)(nil),                      // 6: gamingplatform.api.identity.v1.Bot
}
var file_gamingplatform_api_identity_v1_messaging_proto_depIdxs = []int32{
	6, // 0: gamingplatform.api.identity.v1.GetBotByUsernameResponse.bot:type_name -> gamingplatform.api.identity.v1.Bot
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gamingplatform_api_identity_v1_messaging_proto_init() }
func file_gamingplatform_api_identity_v1_messaging_proto_init() {
	if File_gamingplatform_api_identity_v1_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamingplatform_api_identity_v1_messaging_proto_goTypes,
		DependencyIndexes: file_gamingplatform_api_identity_v1_messaging_proto_depIdxs,
		MessageInfos:      file_gamingplatform_api_identity_v1_messaging_proto_msgTypes,
	}.Build()
	File_gamingplatform_api_identity_v1_messaging_proto = out.File
	file_gamingplatform_api_identity_v1_messaging_proto_goTypes = nil
	file_gamingplatform_api_identity_v1_messaging_proto_depIdxs = nil
}
