// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gamingplatform/api/identity/v1/messaging.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserArrived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserArrived) Reset() {
	*x = UserArrived{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserArrived) ProtoMessage() {}

func (x *UserArrived) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserArrived.ProtoReflect.Descriptor instead.
func (*UserArrived) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *UserArrived) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserSignedUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignedUp) Reset() {
	*x = UserSignedUp{}
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignedUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignedUp) ProtoMessage() {}

func (x *UserSignedUp) ProtoReflect() protoreflect.Message {
	mi := &file_gamingplatform_api_identity_v1_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignedUp.ProtoReflect.Descriptor instead.
func (*UserSignedUp) Descriptor() ([]byte, []int) {
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *UserSignedUp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSignedUp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSignedUp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_gamingplatform_api_identity_v1_messaging_proto protoreflect.FileDescriptor

const file_gamingplatform_api_identity_v1_messaging_proto_rawDesc = "" +
	"\n" +
	".gamingplatform/api/identity/v1/messaging.proto\x12\x1egamingplatform.api.identity.v1\"&\n" +
	"\vUserArrived\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\fUserSignedUp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05emailBfZ\x16identity/v1;identityv1\xca\x02\x1eGamingPlatform\\Api\\Identity\\V1\xe2\x02*GamingPlatform\\Api\\GPBMetadata\\Identity\\V1b\x06proto3"

var (
	file_gamingplatform_api_identity_v1_messaging_proto_rawDescOnce sync.Once
	file_gamingplatform_api_identity_v1_messaging_proto_rawDescData []byte
)

func file_gamingplatform_api_identity_v1_messaging_proto_rawDescGZIP() []byte {
	file_gamingplatform_api_identity_v1_messaging_proto_rawDescOnce.Do(func() {
		file_gamingplatform_api_identity_v1_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc)))
	})
	return file_gamingplatform_api_identity_v1_messaging_proto_rawDescData
}

var file_gamingplatform_api_identity_v1_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gamingplatform_api_identity_v1_messaging_proto_goTypes = []any{
	(*UserArrived)(nil),  // 0: gamingplatform.api.identity.v1.UserArrived
	(*UserSignedUp)(nil), // 1: gamingplatform.api.identity.v1.UserSignedUp
}
var file_gamingplatform_api_identity_v1_messaging_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gamingplatform_api_identity_v1_messaging_proto_init() }
func file_gamingplatform_api_identity_v1_messaging_proto_init() {
	if File_gamingplatform_api_identity_v1_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc), len(file_gamingplatform_api_identity_v1_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamingplatform_api_identity_v1_messaging_proto_goTypes,
		DependencyIndexes: file_gamingplatform_api_identity_v1_messaging_proto_depIdxs,
		MessageInfos:      file_gamingplatform_api_identity_v1_messaging_proto_msgTypes,
	}.Build()
	File_gamingplatform_api_identity_v1_messaging_proto = out.File
	file_gamingplatform_api_identity_v1_messaging_proto_goTypes = nil
	file_gamingplatform_api_identity_v1_messaging_proto_depIdxs = nil
}
