<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.connectfour.v1.Game</code>
 */
class Game extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     */
    protected $game_id = '';
    /**
     * Generated from protobuf field <code>string red_player_id = 2;</code>
     */
    protected $red_player_id = '';
    /**
     * Generated from protobuf field <code>string yellow_player_id = 3;</code>
     */
    protected $yellow_player_id = '';
    /**
     * Generated from protobuf field <code>string current_player_id = 4;</code>
     */
    protected $current_player_id = '';
    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.connectfour.v1.Game.Move moves = 5;</code>
     */
    private $moves;
    /**
     * Generated from protobuf field <code>int32 width = 6;</code>
     */
    protected $width = 0;
    /**
     * Generated from protobuf field <code>int32 height = 7;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>string chat_id = 8;</code>
     */
    protected $chat_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $game_id
     *     @type string $red_player_id
     *     @type string $yellow_player_id
     *     @type string $current_player_id
     *     @type array<\GamingPlatform\Api\ConnectFour\V1\Game\Move>|\Google\Protobuf\Internal\RepeatedField $moves
     *     @type int $width
     *     @type int $height
     *     @type string $chat_id
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\ConnectFour\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->game_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string red_player_id = 2;</code>
     * @return string
     */
    public function getRedPlayerId()
    {
        return $this->red_player_id;
    }

    /**
     * Generated from protobuf field <code>string red_player_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRedPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->red_player_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string yellow_player_id = 3;</code>
     * @return string
     */
    public function getYellowPlayerId()
    {
        return $this->yellow_player_id;
    }

    /**
     * Generated from protobuf field <code>string yellow_player_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setYellowPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->yellow_player_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string current_player_id = 4;</code>
     * @return string
     */
    public function getCurrentPlayerId()
    {
        return $this->current_player_id;
    }

    /**
     * Generated from protobuf field <code>string current_player_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrentPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->current_player_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.connectfour.v1.Game.Move moves = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMoves()
    {
        return $this->moves;
    }

    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.connectfour.v1.Game.Move moves = 5;</code>
     * @param array<\GamingPlatform\Api\ConnectFour\V1\Game\Move>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMoves($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GamingPlatform\Api\ConnectFour\V1\Game\Move::class);
        $this->moves = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 width = 6;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>int32 width = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 7;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chat_id = 8;</code>
     * @return string
     */
    public function getChatId()
    {
        return $this->chat_id;
    }

    /**
     * Generated from protobuf field <code>string chat_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setChatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chat_id = $var;

        return $this;
    }

}

