<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.connectfour.v1.GetOpenGamesResponse</code>
 */
class GetOpenGamesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.connectfour.v1.GetOpenGamesResponse.Game games = 1;</code>
     */
    private $games;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\GamingPlatform\Api\ConnectFour\V1\GetOpenGamesResponse\Game>|\Google\Protobuf\Internal\RepeatedField $games
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\ConnectFour\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.connectfour.v1.GetOpenGamesResponse.Game games = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGames()
    {
        return $this->games;
    }

    /**
     * Generated from protobuf field <code>repeated .gamingplatform.api.connectfour.v1.GetOpenGamesResponse.Game games = 1;</code>
     * @param array<\GamingPlatform\Api\ConnectFour\V1\GetOpenGamesResponse\Game>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GamingPlatform\Api\ConnectFour\V1\GetOpenGamesResponse\Game::class);
        $this->games = $arr;

        return $this;
    }

}

