<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.connectfour.v1.OpenGame</code>
 */
class OpenGame extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string player_id = 1;</code>
     */
    protected $player_id = '';
    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     */
    protected $width = 0;
    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>.gamingplatform.api.connectfour.v1.OpenGame.Stone stone = 4;</code>
     */
    protected $stone = 0;
    /**
     * "move:15000", "game:60000:0", "game:60000:3000"
     *
     * Generated from protobuf field <code>string timer = 5;</code>
     */
    protected $timer = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $player_id
     *     @type int $width
     *     @type int $height
     *     @type int $stone
     *     @type string $timer
     *           "move:15000", "game:60000:0", "game:60000:3000"
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\ConnectFour\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string player_id = 1;</code>
     * @return string
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * Generated from protobuf field <code>string player_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>int32 width = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.connectfour.v1.OpenGame.Stone stone = 4;</code>
     * @return int
     */
    public function getStone()
    {
        return $this->stone;
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.connectfour.v1.OpenGame.Stone stone = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStone($var)
    {
        GPBUtil::checkEnum($var, \GamingPlatform\Api\ConnectFour\V1\OpenGame\Stone::class);
        $this->stone = $var;

        return $this;
    }

    /**
     * "move:15000", "game:60000:0", "game:60000:3000"
     *
     * Generated from protobuf field <code>string timer = 5;</code>
     * @return string
     */
    public function getTimer()
    {
        return $this->timer;
    }

    /**
     * "move:15000", "game:60000:0", "game:60000:3000"
     *
     * Generated from protobuf field <code>string timer = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTimer($var)
    {
        GPBUtil::checkString($var, True);
        $this->timer = $var;

        return $this;
    }

}

