<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/connectfour/v1/messaging.proto

namespace GamingPlatform\Api\ConnectFour\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.connectfour.v1.OpenGameResponse</code>
 */
class OpenGameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     */
    protected $game_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $game_id
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\ConnectFour\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->game_id = $var;

        return $this;
    }

}

