<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/identity/v1/messaging.proto

namespace GamingPlatform\Api\Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.identity.v1.GetBotByUsernameResponse</code>
 */
class GetBotByUsernameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.gamingplatform.api.identity.v1.Bot bot = 1;</code>
     */
    protected $bot = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GamingPlatform\Api\Identity\V1\Bot $bot
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Identity\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.identity.v1.Bot bot = 1;</code>
     * @return \GamingPlatform\Api\Identity\V1\Bot|null
     */
    public function getBot()
    {
        return $this->bot;
    }

    public function hasBot()
    {
        return isset($this->bot);
    }

    public function clearBot()
    {
        unset($this->bot);
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.identity.v1.Bot bot = 1;</code>
     * @param \GamingPlatform\Api\Identity\V1\Bot $var
     * @return $this
     */
    public function setBot($var)
    {
        GPBUtil::checkMessage($var, \GamingPlatform\Api\Identity\V1\Bot::class);
        $this->bot = $var;

        return $this;
    }

}

