<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamingplatform/api/identity/v1/messaging.proto

namespace GamingPlatform\Api\Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gamingplatform.api.identity.v1.GetBotByUsernameResponse</code>
 */
class GetBotByUsernameResponse extends \Google\Protobuf\Internal\Message
{
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GamingPlatform\Api\Identity\V1\GetBotByUsernameResponse\Success $success
     *     @type \GamingPlatform\Api\Common\V1\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GamingPlatform\Api\GPBMetadata\Identity\V1\Messaging::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.identity.v1.GetBotByUsernameResponse.Success success = 1;</code>
     * @return \GamingPlatform\Api\Identity\V1\GetBotByUsernameResponse\Success|null
     */
    public function getSuccess()
    {
        return $this->readOneof(1);
    }

    public function hasSuccess()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.identity.v1.GetBotByUsernameResponse.Success success = 1;</code>
     * @param \GamingPlatform\Api\Identity\V1\GetBotByUsernameResponse\Success $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkMessage($var, \GamingPlatform\Api\Identity\V1\GetBotByUsernameResponse\Success::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.common.v1.Error error = 2;</code>
     * @return \GamingPlatform\Api\Common\V1\Error|null
     */
    public function getError()
    {
        return $this->readOneof(2);
    }

    public function hasError()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.gamingplatform.api.common.v1.Error error = 2;</code>
     * @param \GamingPlatform\Api\Common\V1\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \GamingPlatform\Api\Common\V1\Error::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

